FROM python:3.10-slim
WORKDIR /app

# Instala dependências do sistema necessárias para LightGBM e XGBoost
RUN apt-get update && apt-get install -y \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "-m", "Consumer.avaliador"]